Add type assertion linter
iorvd/uber-go-linter pull request #16
Opened 2022-04-12 21:04 UTC by dmytzo

2022-04-13 09:15 UTC, iorvd requested changes

2022-04-13 09:15 UTC, iorvd commented on linters/linters.go
> +			as, ok := n.(*ast.AssignStmt)
I think we don't need to limit the possible use to assignment only, let's expand it for all possible type assertions.

So we have the following cases here and we need process them all properly:
1. `x, ok := y.(type)` - VALID
2. `x, _ := y.(type)` - INVALID
3. `f(y.(type))` - INVALID
4. `return y.(type)` - INVALID
5. ...

There might be a lot of different options, so I suggest to simplify: the 1st step is to check whether it's a type assertion node or not, the 2nd is to go back in AST and make sure it's a safe type assertion.

WDYT?

2022-04-13 09:18 UTC, dmytzo commented on linters/linters.go
> +			as, ok := n.(*ast.AssignStmt)
thx! good idea, I will try

2022-04-17 09:37 UTC, iorvd commented on linters/linters.go
> +	if len(as.Lhs) != 2 || as.Lhs[1].(*ast.Ident).String() == _BlankIdentifier {
This linter wouldn't pass a run against itself :)

2022-04-17 09:37 UTC, iorvd commented on linters/testdata/src/typeassertion/main.go
>  }
awesome!🕺

2022-04-17 10:12 UTC, dmytzo commented on linters/linters.go
> +	if len(as.Lhs) != 2 || as.Lhs[1].(*ast.Ident).String() == _BlankIdentifier {
I know :)

Updated

2022-04-17 10:15 UTC, dmytzo commented on linters/linters.go
> +func noinit(_ *analysis.Pass, file *ast.File, _ []ast.Node, n ast.Node) error {
I do not think we need to do it already. We can try, when we have some big linters with additional funcs

2022-04-17 10:17 UTC, iorvd approved these changes

2022-04-17 10:27 UTC, merged